.PHONY: all clean cvars
.FORCE:

CXX=g++-10
SDIR=src
ODIR=obj

SRCS=$(wildcard $(SDIR)/*.cpp)
SRCS+=$(wildcard $(SDIR)/hooks/*.cpp)
SRCS+=$(wildcard $(SDIR)/interfaces/*.cpp)
SRCS+=$(wildcard $(SDIR)/sdk/*.cpp)
SRCS+=$(wildcard $(SDIR)/utils/*.cpp)

OBJS=$(patsubst $(SDIR)/%.cpp, $(ODIR)/%.o, $(SRCS))

# Header dependency target files; generated by g++ with -MMD
DEPS=$(OBJS:%.o=%.d)

WARNINGS=-Wall -Wno-parentheses -Wno-unknown-pragmas -Wno-delete-non-virtual-dtor
CXXFLAGS=-std=c++17 -m32 $(WARNINGS) -I$(SDIR) -fPIC -D_GNU_SOURCE -fpermissive
LDFLAGS=-m32 -shared -lstdc++fs

# Import config.mk, which can be used for optional config
-include config.mk

all: wormhole.so

-include $(DEPS)

wormhole.so: $(OBJS)
	$(CXX) $^ $(LDFLAGS) -o $@

$(ODIR)/%.o: $(SDIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -MMD -c $< -o $@
